INSERT INTO images (imageURL, imageType, imageDescription) VALUES
--Stephen
('https://i.imgur.com/jt0vy4o.jpg','AI','Bob'),
('https://i.imgur.com/yzU1l7d.jpg','AI','Bowl'),
('https://i.imgur.com/xUMGSdi.jpg','AI','Cat'),
('https://i.imgur.com/kLosgLf.jpg','AI','Dancing'),
('https://i.imgur.com/Fzup0Jw.jpg','AI','Homecoming'),
('https://i.imgur.com/ahMfCjg.jpg','AI','House'),
('https://i.imgur.com/rV5OjrH.jpg','AI','Jesus'),
('https://i.imgur.com/D4lqEKY.jpg','AI','Panda'),
('https://i.imgur.com/Ceyv64G.jpg','AI','School'),
('https://i.imgur.com/XpXUR4z.jpg','AI','Skull'),
('https://imgc.artprintimages.com/img/print/destination-signs-key-west-florida_u-l-pz52i30.jpg?artHeight=900&artPerspective=n&artWidth=900&background=fbfbfb','Real','Philippe Hugonnard'),
('https://www.boredpanda.com/blog/wp-content/uploads/2018/03/ugly-medieval-cats-art-103-5aafaff5c7b63__700.jpg','Real','Unknown'),
('https://pyxis.nymag.com/v1/imgs/bea/948/f6fcdc2fcbee41e96fdabd3be1cd0faf33-bonhams-cats-lot-68.rhorizontal.w807.jpg','Real','Henriette Ronner-Knip'),
('https://images.fineartamerica.com/images/artworkimages/mediumlarge/3/regal-renaissance-cat-portrait-painting-milly-may.jpg','Real','Milly May'),
('https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/colorful-crazy-lion-deep-dream-matthias-hauser.jpg','Real','Matthias Hauser'),
('https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/woman-with-dog-head-deep-dream-wild-and-crazy-matthias-hauser.jpg','Real','Matthias Hauser'),
('https://www.secondsandsurplus.com/media/amasty/webp/catalog/product/cache/3fe6aec9cc5f6c18d982cfde69d3b17f/a/r/artae2022_jpg.webp','Real','Seconds and Surplus'),
('https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/american-flag-flat-waving-v1-copy-6-roy-wylam.jpg','Real','Roy Wylam'),
('http://cdn.cnn.com/cnnnext/dam/assets/190516115302-h-r-giger-1.jpg','Real','H.R. Giger'),
('https://www.rct.uk/sites/default/files/styles/rctr-scale-1010w/public/256209-1330622370.jpg?itok=5HZ5Wwx_','Real','Portrait of a Man'),
--Nick
--Andrew
('https://imgur.com/wiYF654.jpg','AI',''),
('https://imgur.com/RZ2wXLM.jpg','AI',''),
('https://imgur.com/n5tewlW.jpg','AI',''),
('https://imgur.com/QBu3UI9.jpg','AI',''),
('https://imgur.com/4RDRF9M.jpg','AI',''),
('https://i.imgur.com/Zel1G1F.jpg','AI',''),
('https://i.imgur.com/0aWNwsi.jpg','AI',''),
('https://imgur.com/gEBoH24.jpg','AI',''),
('https://i.imgur.com/gNF2GIH.jpg','AI',''),
('https://i.imgur.com/5DHMplh.jpg','AI',''),
--Zach
--Ian Stewart
('https://images.nightcafe.studio/jobs/DotKrjOyVQLLemHGtDcB/DotKrjOyVQLLemHGtDcB--4--2zgue.jpg?tr=w-1600,c-at_max','AI','dark souls'),
('https://images.nightcafe.studio/jobs/DotKrjOyVQLLemHGtDcB/DotKrjOyVQLLemHGtDcB--1--4uyfc.jpg?tr=w-1600,c-at_max','AI','dark souls'),
('https://images.nightcafe.studio/jobs/DotKrjOyVQLLemHGtDcB/DotKrjOyVQLLemHGtDcB--2--14gdj.jpg?tr=w-1600,c-at_max','AI','dark souls'),
('https://images.nightcafe.studio/jobs/XNWxYAHBJAild2p3eZDY/XNWxYAHBJAild2p3eZDY--3--tbqh2.jpg?tr=w-1600,c-at_max','AI','end of the world'),
('https://images.nightcafe.studio/jobs/XNWxYAHBJAild2p3eZDY/XNWxYAHBJAild2p3eZDY--2--xhjpk.jpg?tr=w-1600,c-at_max','AI','end of the world'),
('https://images.nightcafe.studio/jobs/AeUBLZQyMDDlO7yNGFol/AeUBLZQyMDDlO7yNGFol--2--26jxz.jpg?tr=w-1600,c-at_max','AI','yhorm the giant'),
('https://images.nightcafe.studio/jobs/71JunKppzV3w3n3KC7ay/71JunKppzV3w3n3KC7ay.jpg?tr=w-1600,c-at_max','AI','gates to hell'),
('https://images.nightcafe.studio/jobs/q8oeVT5MgTJw6uKgnydo/q8oeVT5MgTJw6uKgnydo--4--0tniu.jpg?tr=w-1600,c-at_max','AI','sunset over the mountain range'),
('https://images.nightcafe.studio/jobs/q8oeVT5MgTJw6uKgnydo/q8oeVT5MgTJw6uKgnydo--3--be15v.jpg?tr=w-1600,c-at_max','AI','sunset over the mountain range'),
('https://images.nightcafe.studio/jobs/jn2JLN4rTdg2RQ6p51vX/jn2JLN4rTdg2RQ6p51vX--1--zxdif.jpg?tr=w-1600,c-at_max','AI','jungle canopy'),
('https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/bloodborne-art-oleksandr-vaznichenko.jpg','Real','Oleksandr Vaznichenko'),
('https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/9a8c87dc-a37a-4194-b8a6-c27e807996c6/dcvb5yv-9e82d010-6218-4866-8250-635d072d254d.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzlhOGM4N2RjLWEzN2EtNDE5NC1iOGE2LWMyN2U4MDc5OTZjNlwvZGN2YjV5di05ZTgyZDAxMC02MjE4LTQ4NjYtODI1MC02MzVkMDcyZDI1NGQuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.tg6wFR6l4GplQkEHzjQImuqtDr9YmT5C1kC06blUeDA','Real','BarsonYouTube'),
('https://res.cloudinary.com/cook-becker/image/fetch/q_auto,f_auto,w_1920,e_sharpen/https://candb.com/site/candb/images/artwork/kiln-of-the-first-flame-dark-souls-3-from-software.jpg','Real','Cook and becker'),
('https://images.fineartamerica.com/images/artworkimages/mediumlarge/3/dark-souls-3-juan-harris.jpg','Real','Juan Harris'),
('https://cdnb.artstation.com/p/assets/images/images/000/523/489/large/brandon-fernandes-ds2.jpg?1425562147 ','Real','Brandon Fernandes'),
('https://ih1.redbubble.net/image.2891604595.1720/flat,750x,075,f-pad,750x1000,f8f8f8.jpg','Real','Ali Shimhaq'),
('https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/24e28a28-6fcb-4981-8385-c8c666433680/d464vj0-9d566f0c-21f5-4bd6-aac2-8c844fe2fb4d.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzI0ZTI4YTI4LTZmY2ItNDk4MS04Mzg1LWM4YzY2NjQzMzY4MFwvZDQ2NHZqMC05ZDU2NmYwYy0yMWY1LTRiZDYtYWFjMi04Yzg0NGZlMmZiNGQuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.mJIUNFHchoZ_ORJeXbl6QCjy1Rcj-b0fmlcyaAkmawc','Real','renata-studio'),
('https://img.artpal.com/96513/5-15-3-8-15-42-4m.jpg','Real','Steve Armstrong'),
('https://www.simplemost.com/wp-content/uploads/2021/12/AdobeStock_125898822.jpeg','Real','vovik_mar'),
('https://i.pinimg.com/originals/70/83/e0/7083e058abafbaa41e0284f8cfa4fbc7.jpg','Real','Charles Hartley'),
--Ian Von Pechmann
('https://i.imgur.com/wv2417y.png','AI',''),
('https://i.imgur.com/lWj9S7x.png','AI',''),
('https://i.imgur.com/IhrjkCx.png','AI',''),
('https://i.imgur.com/5MiLbos.jpg','AI',''),
('https://i.imgur.com/GPZoraH.jpg','AI',''),
('https://i.imgur.com/LBDH43N.jpg','AI',''),
('https://i.imgur.com/tgMdyMN.jpg','AI',''),
('https://i.imgur.com/bpmWbu8.jpg','AI',''),
('https://i.imgur.com/X6Q1wgV.jpg','AI',''),
('https://i.imgur.com/nesXgXr.jpg','AI',''),
('https://render.fineartamerica.com/images/rendered/default/print/6.5/8/break/images/artworkimages/medium/1/african-lion-lucie-bilodeau.jpg','Real',''),
('https://www.novica.com/blog/wp-content/uploads/2016/09/lordofjungle.jpg','Real',''),
('https://www.parkwestgallery.com/wp-content/uploads/2018/09/884156-lets-make-a-wish_ilyayev-jpg.jpg','Real',''),
('https://i.etsystatic.com/5150206/r/il/1dd83b/1785974556/il_fullxfull.1785974556_696x.jpg','Real',''),
('https://www.this-is-cool.co.uk/wp-content/gallery/koveck-art/the-art-of-koveck-11.jpg','Real',''),
('https://images.fineartamerica.com/images-medium-large-5/dark-sea-demoncio.jpg','Real',''),
('https://images.fineartamerica.com/images/artworkimages/mediumlarge/3/the-post-apocalyptic-world-realiten-digital-art.jpg','Real',''),
('https://c4.wallpaperflare.com/wallpaper/924/878/435/sta%C5%84czyk-digital-art-joker-wallpaper-thumb.jpg','Real',''),
('https://images.saatchiart.com/saatchi/696454/art/6518701/5588377-HSC00002-7.jpg','Real',''),
('https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/surreal-tiger-bubble-water-dancer-daniel-eskridge.jpg','Real','');
